// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCg5J2R4fGefZ7qCuERSyqdptZ-MKz-X9U',
    appId: '1:374654796736:web:445fd323c9a604e7117e25',
    messagingSenderId: '374654796736',
    projectId: 'crudtutorial-700a6',
    authDomain: 'crudtutorial-700a6.firebaseapp.com',
    storageBucket: 'crudtutorial-700a6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvBpZVgdvyeoOgfDp3YIb0hB14DIO-0UA',
    appId: '1:374654796736:android:b125e4fa06c7b10d117e25',
    messagingSenderId: '374654796736',
    projectId: 'crudtutorial-700a6',
    storageBucket: 'crudtutorial-700a6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCVT1jWoKTdp2HlfRhy4wI7AJ26ZTuYbw',
    appId: '1:374654796736:ios:c30a4fc7a8537146117e25',
    messagingSenderId: '374654796736',
    projectId: 'crudtutorial-700a6',
    storageBucket: 'crudtutorial-700a6.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCVT1jWoKTdp2HlfRhy4wI7AJ26ZTuYbw',
    appId: '1:374654796736:ios:c30a4fc7a8537146117e25',
    messagingSenderId: '374654796736',
    projectId: 'crudtutorial-700a6',
    storageBucket: 'crudtutorial-700a6.appspot.com',
    iosBundleId: 'com.example.crudApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCg5J2R4fGefZ7qCuERSyqdptZ-MKz-X9U',
    appId: '1:374654796736:web:b21160568a8b6163117e25',
    messagingSenderId: '374654796736',
    projectId: 'crudtutorial-700a6',
    authDomain: 'crudtutorial-700a6.firebaseapp.com',
    storageBucket: 'crudtutorial-700a6.appspot.com',
  );
}
